### ISSUE TITLE
Add simdjson

### ISSUE THREAD

**Issue by myd7349** [miloyip/nativejson-benchmark#113]
https://github.com/lemire/simdjson

**Comment by scarsty** [comment]
it should be great

**Comment by mloskot** [comment]
The library offers its own performance comparison against RapidJSON
https://github.com/lemire/simdjson#performance-results

**Comment by mohsenomidi** [comment]
Hello to everyone 

Would you please add this library benchmarks here to compare with others, especially RapidJSON, the owner of library benchmarks says it is better than RapidJSON, but we need same benchmark tests, to have a valid compare results, it seems it is very fast only on heavy weight json... 
but needs to have a same benchmark procedures, if it’s possible please add it asap

Best Regards

**Comment by mloskot** [comment]
Asking someone to volunteer do something *asap* is remotely polite. Please, FFS, stop asking and start contributing!

**Comment by mohsenomidi** [comment]
@mloskot, i am sorry to ask impolitely, i thought it was forgotten because this case opened 10 months ago, and I don’t know the conversation rules as well as native English spokesperson...may its miss understanding in my bad writing, my point was Please don’t forget this issue And it was polite in my mind :)
Anyway, I don’t know the procedures to be a contributor, if you can share it, may i can help to writing some simple c++ functions to make it feasible...

**Comment by mloskot** [comment]
I think this can be closed as https://github.com/miloyip/nativejson-benchmark/pull/131 has been merged

**Comment by reedgra** [comment]
But it is not appearing in the charts?
